import type { Metadata } from "next";
import { Open_Sans , Poppins } from "next/font/google";
import "./globals.css";
import { ClientPrevider } from "./reduxstore/ClientProvider";
import { TopLayer } from "./components/TopLayer";

const poppins = Poppins({ subsets: ["latin"] , weight : ['400','500','600'] });


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <ClientPrevider>
          <TopLayer />
          {children}
        </ClientPrevider>
      </body>
    </html>
  );
}
